name = "test_gh_workflows"
uuid = "0ed0cc52-a512-4171-b66b-ec8e7cbd9005"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de"]
version = "0.1.0"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
